# Generated by Django 5.0.7 on 2024-07-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
