# Generated by Django 5.0.7 on 2024-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_bookmark_user_alter_bookmark_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
